# put here any directive needed only when deploying
# a special deploy_dir variable specifies the deployment location using rsync

baseurl: http://AlanJui.github.io/
deploy_dir: git@github.com:AlanJui/AlanJui.github.io.git

