title: 阿中的網路筆記本
description: 學而時習之，筆記備忘知

url: http://jekyll.ccc99.tw/
#url: http://alanjui.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
#permalink: blog/:categories/:year/:month/:day/:title/
#permalink: pretty
#permalink: blog/:categories/:year/:month/:day/:title.html
permalink: date

markdown: redcarpet
#markdown: kramdown
highlighter: pygments
paginate: 10

navigation:
 - title: 首頁
   url: /index.html
 - title: 歸檔
   url: /archived.html
 - title: 關於我
   url: /about.html
 - title: 聯絡我
   url: /contact.html
 - title: 標籤
   url: /tags

social:
   github: AlanJui
   twitter: AlanJui
   facebook: AlanJui
   email: alanjui.1960@gmail.com

google_analytics: "UA-62038067-2"
