title: CCC生活札記
description: 凡走過必留下痕跡；既活著總得留點筆記

url: http://alanjui.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 首頁
   url: /index.html
 - title: 關於我
   url: /about.html
 - title: 聯絡我
   url: /contact.html

social:
   github: AlanJui
   twitter: AlanJui
   facebook: AlanJui
   email: alanjui.1960@gmail.com

google_analytics: "UA-58263416-1"
